### ISSUE TITLE
BaseBlockDivider issue

### ISSUE THREAD

**Issue by skapix** [mmcsOptimizingCompilers2016/pile#42]
code sample
```
{
	c = a + 3;
	d = d + d;
	b = a + 2;
	d = a + 2;
	e = 3 + a;
	if e > 3
	{
		k = a + 4;
		z = a + 3;
	}
	z = a + 3;
}
```

**Comment by artemkonenko** [comment]
Это пример программы, где нулевой блок становится пустым? Не воспроизводится ни до, ни, тем более, после фикса баги с переходом на первую строчку.

Раньше ошибка воспроизводилась программой
```
{
	while e > 3 do
	{
		k = a + 4;
		z = a + 3;
	}

	c = a + 3;
	d = d + d;
	b = a + 2;
}
```

Но после слияния с веткой, где эта ошибка исправлена, всё починилось.

**Comment by skapix** [comment]
это пример программы с неверной установкой поля Predecessors

```
Block: B0
          c := a + 3
          d := d + d
          b := a + 2
          d := a + 2
          e := 3 + a
          $t0 := e > 3
          if $t0 goto %l0

Block: B1
          goto %l1

Block: B2
%l0:      nop
          k := a + 4
          z := a + 3

Block: B3
%l1:      nop
          z := a + 3
```

B1 не является предшественником B2

**Comment by artemkonenko** [comment]
@skapix Ок, увидел ошибку и уже понял как исправить, к вечеру будет.
